#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Using redis host $TEST_REDIS_HOST"

export TEST_REDIS_HOST

pushd $SCRIPT_DIR
mkdir -p ../../output/test-reports/
rm -f luacov.*
busted -c --output=junit . >  ../../output/test-reports/redis-lua.xml || true
cat luacov.report.out
popd
