#!/bin/bash

if [[ -n $(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD|grep -E '(package.json|npm-shrinkwrap.json)') ]]; then
  echo "Packaging has changed. Performing an npm install"
  npm prune
  npm install
fi
